
#spring.mvc.pathmatch.matching-strategy : ant_path_matcher
server.port: 8020

spring:
  flyway:
    outOfOrder: true
  database-platform=org:
    hibernate:
      dialect: MySQL5InnoDBDialect
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ticket_booking
    username: root
    password: siva2001







